kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  environment:
   CouchDB_URL:
    from_secret: couchdb_url
   CouchDB_PASSWORD:
    from_secret: couchdb_password
   CouchDB_USERNAME:
    from_secret: couchdb_user

  settings:
    username: 
        from_secret: docker_username
    password:
        from_secret: docker_password
    repo: mawokamyblock/vocabserver
    tags: dev
    build_args:
     - CouchDB_URL
     - CouchDB_PASSWORD
     - CouchDB_USERNAME
  when:
    branch:
      - master