version: "3"
volumes:
  couchdb_data:



services:
  couchdb:
    image: couchdb:3.1.1
    container_name: couchdb
    #volumes:
      #- couchdb_data:/opt/couchdb/data
      #- ${DOCKER_VOLUMES_BASEPATH}/couchdb_log:/var/log/couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
#    ports:
#      - "5984:5984"
    restart:
      unless-stopped
    networks:
      - appnet
    volumes:
      - ./couchdb:/opt/couchdb/etc/local.d

  vocabserver:
    build: .
    container_name: vocabserver
    restart:
      unless-stopped
    depends_on:
      couchdb:
        condition: service_started
    ports:
      - 80:80
    networks:
      - appnet
    environment:
      - CouchDB_URL=http://couchdb:5984
      - CouchDB_USERNAME=admin
      - CouchDB_PASSWORD=password



networks:
  appnet:
    name: appnet





