site_name: MyDocs
theme:
site_dir: public
  name: material
  custom_dir: docs/overrides
  palette:
        # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top



markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.progressbar


nav:
  - About: index.md
  - Setup:
    - Installation: installation.md
  - APIs:
    - Authentification:
        - authapi.md
        - userapi.md
    - studentapi.md
    - vocabapi.md
plugins:
  - search
