terminal:
  # This can be any image that has the necessary runtime environment for your project.
  image: python:latest
  before_script:
    - apt-get update
    - pip install -r requirements.txt
  script: uvicorn main:app --reload
  variables:
    RAILS_ENV: "test"
    NODE_ENV: "test"
