name: scp files
on:
  workflow_dispatch:
jobs:

  build:
    name: Upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "/*.py, interface/, *.ini, static/, templates/, *.txt,"
        target: "/home/ciuser/vocabserver"
    - name: Update
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script:  systemctl --user restart vocabserver.service
